*&---------------------------------------------------------------------*
*&  Include           ZSHIPAGILE_STARTER_PROGRAM_SEL
*&---------------------------------------------------------------------*


DATA: ls_but1,ls_but2 TYPE char20.

*****Selection Screen**************

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-005.
PARAMETERS: p_file TYPE  char100.
SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-002.
SELECTION-SCREEN COMMENT 1(40) TEXT-001.
SELECTION-SCREEN PUSHBUTTON 41(20) but1 USER-COMMAND b1.
SELECTION-SCREEN SKIP  1.
SELECTION-SCREEN END OF BLOCK b2.

SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE TEXT-003.
SELECTION-SCREEN COMMENT 1(40) TEXT-004.
SELECTION-SCREEN PUSHBUTTON 41(20) but2 USER-COMMAND b2.
SELECTION-SCREEN SKIP  1.
SELECTION-SCREEN END OF BLOCK b3.


SELECTION-SCREEN BEGIN OF BLOCK b4 WITH FRAME TITLE TEXT-006.
SELECTION-SCREEN COMMENT 1(40) TEXT-007.
SELECTION-SCREEN PUSHBUTTON 41(20) but3 USER-COMMAND b3.
SELECTION-SCREEN SKIP  1.
SELECTION-SCREEN END OF BLOCK b4.
*****Selection Screen**************
