*&---------------------------------------------------------------------*
*&  Include           ZSHIPAGILE_STARTER_PROGRAM_SEL
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK b20 WITH FRAME." TITLE TEXT-005.
 SELECTION-SCREEN BEGIN OF BLOCK b21 WITH FRAME.
PARAMETERS: p_file TYPE  char100.
* comment
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT /01(74) comm01.
SELECTION-SCREEN COMMENT /01(74) comm02.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN COMMENT /01(74) comm03.
SELECTION-SCREEN COMMENT /01(74) comm04.
SELECTION-SCREEN SKIP 1.
*SELECTION-SCREEN COMMENT /05(70) text-007.
*SELECTION-SCREEN COMMENT /05(70) text-008.
*SELECTION-SCREEN SKIP 1.
*SELECTION-SCREEN COMMENT /05(70) text-009.
*SELECTION-SCREEN COMMENT /05(70) text-010.
* comment.
SELECTION-SCREEN END OF BLOCK b21.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME." TITLE TEXT-003.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN PUSHBUTTON 1(54) but1 USER-COMMAND b1.
SELECTION-SCREEN COMMENT 60(6) TEXT-011 FOR FIELD p_but1.
PARAMETERS p_but1 TYPE char4 MODIF ID p1 DEFAULT icon_red_light.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP  1.
SELECTION-SCREEN END OF BLOCK b1.

*
SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME." TITLE TEXT-002.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN PUSHBUTTON 1(54) but2 USER-COMMAND b2.
SELECTION-SCREEN COMMENT 60(6) TEXT-011 FOR FIELD p_but2.
PARAMETERS p_but2 TYPE char4 MODIF ID p1 DEFAULT icon_red_light.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP  1.
SELECTION-SCREEN END OF BLOCK b2.
*
*
SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME ."TITLE TEXT-006.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN PUSHBUTTON 1(54) but3 USER-COMMAND b3.
SELECTION-SCREEN COMMENT 60(6) TEXT-011 FOR FIELD p_but3.
PARAMETERS p_but3 TYPE char4 MODIF ID p1 DEFAULT icon_red_light.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP  1.
SELECTION-SCREEN END OF BLOCK b3.

SELECTION-SCREEN BEGIN OF BLOCK b4 WITH FRAME ."TITLE TEXT-006.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN PUSHBUTTON 1(54) but4 USER-COMMAND b4.
SELECTION-SCREEN COMMENT 60(6) TEXT-011 FOR FIELD p_but4.
PARAMETERS p_but4 TYPE char4 MODIF ID p1 DEFAULT icon_red_light.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP  1.
SELECTION-SCREEN END OF BLOCK b4.
SELECTION-SCREEN END OF BLOCK b20.
